# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"
DISTUTILS_SRC_TEST="setup.py"

inherit distutils


DESCRIPTION="VMware vSphere Python SDK"
HOMEPAGE="https://github.com/vmware/pyvmomi"
SRC_URI="https://pypi.python.org/packages/44/94/0306e0d5fe8454edcb58eb9ede60be5ec58a46213945877bc79c43baffc3/${P}.tar.gz"

LICENSE="Apache-2.0"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/requests-2.3.0
	>=dev-python/six-1.7.3
	dev-python/setuptools
	test? ( >=dev-python/testtools-0.9.34 )
	test? ( dev-python/vcrpy )"
