# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="5"
PYTHON_COMPAT=( python2_7 python3_4 python3_5 )

inherit distutils-r1

DESCRIPTION="VMware vSphere Python SDK"
HOMEPAGE="https://github.com/vmware/pyvmomi"
SRC_URI="mirror://pypi/${P:0:1}/${PN}/${P}.tar.gz"

LICENSE="Apache-2.0"
KEYWORDS="~amd64"
SLOT="0"
IUSE="test"

DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/requests-2.3.0
	>=dev-python/six-1.7.3
	dev-python/setuptools
	test? ( >=dev-python/testtools-0.9.34 )
	test? ( dev-python/vcrpy )"
